INSERT INTO tasks (title, description, status, due_date, priority, created_at, updated_at)
VALUES
('Task1', 'Task 1', 'TODO', DATEADD('DAY', 2, CURRENT_TIMESTAMP), 'HIGH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Task2', 'Task 2', 'DONE', DATEADD('DAY', -1, CURRENT_TIMESTAMP), 'LOW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Task3', 'Task 3', 'IN_PROGRESS', DATEADD('DAY', 1, CURRENT_TIMESTAMP), 'MEDIUM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
